# Generated by Django 5.0.8 on 2024-10-05 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_notafiscal_remove_venda_produto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valida',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ExclusaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.venda')),
            ],
        ),
    ]
