# Generated by Django 5.0.8 on 2024-11-15 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_venda_valida_exclusaovenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
